name: Keep Render Bot Alive

on:
  schedule:
    # This cron expression runs the job every 10 minutes
    - cron: '*/10 * * * *'
  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch: 

jobs:
  ping-service:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: |
          curl -I -s https://workflowtrigger-bot-nnft.onrender.com/
